# Generated by Django 4.1.2 on 2022-11-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stock_stock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_data',
            field=models.FileField(upload_to='stocks/'),
        ),
    ]
